### ISSUE TITLE
[NFR]: Compatibility with `psr/simple-cache` 2.x and 3.x

### ISSUE THREAD

**Issue by StudioMaX** [phalcon/proxy-psr16#3]
**Is your feature request related to a problem? Please describe.**
It is not possible to use the latest version of the database migration manager `robmorgan/phinx` because in the latest versions they require `psr/simple-cache` `^2.0 || ^3.0` through the dependency chain.

Now the composer.json contains the requirement for `"psr/simple-cache": "^1.0"`. Is there any reason why there is no support for newer versions of `psr/simple-cache` - 2.0.0 and 3.0.0, even though they were released back in 2021?

**Describe the solution you'd like**
Add the ability to install `psr/simple-cache` `^2.0 || ^3.0`.

**Describe alternatives you've considered**

**Additional context**

```
  Problem 1
    - Root composer.json requires phalcon/proxy-psr16 ^1.0 -> satisfiable by phalcon/proxy-psr16[1.0.0].
    - cakephp/datasource 5.0.0 requires psr/simple-cache ^2.0 || ^3.0 -> satisfiable by psr/simple-cache[2.0.0, 3.0.0].
    - cakephp/database 5.0.0 requires cakephp/datasource ^5.0 -> satisfiable by cakephp/datasource[5.0.0].
    - You can only install one version of a package, so only one of these can be installed: psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 3.0.0].
    - robmorgan/phinx[0.15.0, ..., 0.15.2] require cakephp/database ^5.0 -> satisfiable by cakephp/database[5.0.0].
    - phalcon/proxy-psr16 1.0.0 requires psr/simple-cache ^1.0 -> satisfiable by psr/simple-cache[1.0.0, 1.0.1].
    - Root composer.json requires robmorgan/phinx ^0.15 -> satisfiable by robmorgan/phinx[0.15.0, 0.15.1, 0.15.2].
```

**Comment by niden** [comment]
@StudioMaX Thank you for this.

New release fixes that: https://github.com/phalcon/proxy-psr16/releases/tag/2.0.0

psr/simple-cache v2/v3 work only in PHP 8+, hence this new version allows for upgrading. For those that need this while using PHP 7.4 can use v1.0.0
