### ISSUE TITLE
[BUG]: typed parameter compatibility issues 

### ISSUE THREAD

**Issue by ALameLlama** [phalcon/proxy-psr16#5]
**Describe the bug**
When trying to implement PHP Domain Parser
https://github.com/jeremykendall/php-domain-parser/blob/92709ef1e58ef57e24571a1129b112f58b596976/README.md
Towards the bottom, you can see an implementation using a PsrStorageFactory. This first param is typed as Psr\SimpleCache\CacheInterface

Trying to use this proxy will cause this error on a bunch of functions
```
Declaration of Phalcon\Proxy\Psr16\Cache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed
```

**To Reproduce**

```php
            $redisCache =  new \Phalcon\Cache\Adapter\Redis(
                $this->getShared('serializerFactory'),
                $redisConfig
            );

            $factory = new PsrStorageFactory(
                new \Phalcon\Proxy\Psr16\Cache($redisCache),
                new \GuzzleHttp\Client(),
                $requestFactory
            );
```

**Expected behavior**
For the proxy to to work with Psr\SimpleCache\CacheInterface

**Details**
 - Phalcon version: 5.3.1
 - PHP Version: 8.1
 - Operating System: Ubuntu 20
 - Server: Apache

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/proxy-psr16/pull/6

Thank you @ALameLlama . I will update composer and make a new release.
